### ISSUE TITLE
Remove Load more button and automatically load movies while scrolling

### ISSUE THREAD

**Issue by tarunyadav1** [tarunyadav1/Movie-Library-App-using-Reactjs-and-The-MovieDB-API#5]
Autoload movies while scrolling the homepage. Remove the load more button.

**Comment by julieg18** [comment]
I'd be happy to help!

**Comment by tarunyadav1** [comment]
okay @julieg18

**Comment by MuhammadTanveer94** [comment]
i would like to do this @tarunyadav1 ?

**Comment by tarunyadav1** [comment]
Hey, @MuhammadTanveer94  I have already assigned.
